#!/bin/sh
#rst2pdf presentation.rst -b1 -s slides.style
#rst2pdf 01*.rst -e inkscape -b1 -s slides.style
#rst2pdf 02*.rst -e inkscape -b1 -s slides.style
rst2pdf 03*.rst -e inkscape -b1 -s slides.style
#open presentation.pdf
